services:
  postgres:
    image: postgres:15
    container_name: community-postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: community
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "1234"
    volumes:
      - community-postgres-data:/var/lib/postgresql/data

volumes:
  community-postgres-data:
